version: '3'
services:
  mongodb-burger:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=crwn-clothing-db
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=welcome1
    volumes:
      - mongodb:/data/crwn-clothing/db
    ports:
      - 27017:27017
    networks:
      - mongo_net

volumes:
  mongodb:

networks:
  mongo_net:
    driver: bridge